temporarily disabled verify step

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -16,24 +16,24 @@ jobs:
     #   with:
     #     node-version: ${{ env.NODE_VERSION }}
 
-    - name: Verify Files
-      run: |
-        illegal_files=(package-lock.json build/)
-        essential_files=(package.json yarn.lock README.md tsconfig.json .gitignore src/ public/)
+    # - name: Verify Files
+    #   run: |
+    #     illegal_files=(package-lock.json build/)
+    #     essential_files=(package.json yarn.lock README.md tsconfig.json .gitignore src/ public/)
 
-        for f in $illegal_files; do
-          if [ -e $f ]
-            echo "Found an illegal file $f - Please remove it"
-            exit 1
-          fi
-        done
+    #     for f in $illegal_files; do
+    #       if [ -e $f ]
+    #         echo "Found an illegal file $f - Please remove it"
+    #         exit 1
+    #       fi
+    #     done
 
-        for f in $essential_files; do
-          if [ ! -e $f ]
-            echo "Could not find essential file $f - Please make sure it's included"
-            exit 2
-          fi
-        done
+    #     for f in $essential_files; do
+    #       if [ ! -e $f ]
+    #         echo "Could not find essential file $f - Please make sure it's included"
+    #         exit 2
+    #       fi
+    #     done
 
     - name: "Cache: Setup"
       id: yarn-cache-setup
